# // Step One : Access the csv file and its data

import smtplib
fh = open("candidatepmp.csv")
#fh = open("candidates21.csv")

data = []

for line in fh:
    strip = line.rstrip()
    candidate = strip.split(",")
    candidate = candidate[0].upper(),candidate[3],candidate[4]
    data.append(candidate)
# print(data)
print(len(data))

# Step 2 : Connect and login to the server

server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
sender = input('Enter you email') 
password = input("Enter your passowrd: ")
# You need generate a password for thrid party app in google mail for this project
server.login( sender , password)


# Step 3 : Send the email message to individual in csv file
for recv in data:
    candidateName = recv[0]
    course = recv[2]   
    subject = "Sending a test Email"
    text    = f'''
    Dear {candidateName},

    This is to inform you that NAVTTC-TIME under "Kamyab Jawan Skills for All program" 
    is accepting applications to enroll candidates in Project Management Certification. 
    
    In order to avail this FREE course with highly demanding NAVTTC certificate, you are
    required to apply online at https://pms.navttc.gov.pk/admission and submit the documents
    1- Copy of CNIC
    2- 2 passport size photographs
    3- Educational Documents
    at Bungalow No: A-9, Mir Hussainabad, behind Sindh Seed Corporation, Hyderabad. 
    
    As you were previously interested in {course}, therefore we are considering you as the 
    potentional candidate.
     
    LAST DATE OF REGISTRATION IS 31-JAN-2022.
    
    Note1: This is an autogenerated email.
    Note: 
    1- Please collect your receipt after submitting documents.
    2- If you are below 18 or above 40 your form will be rejected automatically.
    3- If you have already availed any course sponsored by NAVTTC then you can not 
    avail the opportunity again.
    
    In case of querry contact 022-3820070
    
    Regards
    Abrar Hussain Tunio
    Director TIME

    '''
                
        
    message = 'Subject: {}\n\n{}'.format(subject, text)
    server.sendmail(sender,recv[1],message)
    print(sender, recv[1])
